name: CI

on:
  push:
    tags: 
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: ["8.0.x", "10.0.x"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore solution
        run: dotnet restore FFmpegVideoPlayer.Avalonia.sln

      - name: Package Solution
        run: dotnet pack FFmpegVideoPlayer.Avalonia.sln -c Release --output ./artifacts

      - name: Push to GitHub Packages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --skip-duplicate